# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"6\n\tMessage_t\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\nReceived_t\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x35\n\tService_t\x12(\n\x0b\x43ommunicate\x12\n.Message_t\x1a\x0b.Received_t\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE_T']._serialized_start=14
  _globals['_MESSAGE_T']._serialized_end=68
  _globals['_RECEIVED_T']._serialized_start=70
  _globals['_RECEIVED_T']._serialized_end=99
  _globals['_SERVICE_T']._serialized_start=101
  _globals['_SERVICE_T']._serialized_end=154
# @@protoc_insertion_point(module_scope)
